Repository Canard-Ecarlate/Backend, pull requests merged in 2022-03, with the labels that each got.

#169 141 Mettre en place le déploiement du backend
  DuckCity.Api/Controllers/SshController.cs
  DuckCity.Api/appsettings.json
  DuckCity.Application/ContainerGameApiService/GameContainerService.cs
  DuckCity.GameApi/Dockerfile
  DuckCity.GameApi/appsettings.json
Labels: Backend, Deployement

#171 maj docker game api
  DuckCity.Application/ContainerGameApiService/GameContainerService.cs
Labels: Backend, Improvement, Deployement

#174 173 Mise en place de logs dans le hub
  DuckCity.GameApi/Hub/DuckCityHub.cs
Labels: Backend, Improvement

#175 173 Mise en place de logs dans le hub
  DuckCity.GameApi/Hub/DuckCityHub.cs
Labels: Backend, Improvement

#177 176 Fix bug push players on reconnect
  DuckCity.GameApi/Hub/DuckCityHub.cs
Labels: Bug, Backend

#179 176 Fix bug push players on reconnect
  DuckCity.Application/RoomService/RoomService.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.Infrastructure/RoomRepository/RoomCacheRepository.cs
  DuckCity.Tests/UnitTests/Application/RoomServiceUt.cs
Labels: Bug, Backend
