Repository Canard-Ecarlate/Backend, pull requests merged in 2022-02, with the labels that each got.

#125 Refacto Player unique
  DuckCity.Api/Controllers/RoomController.cs
  DuckCity.Api/Program.cs
  DuckCity.Application/Services/AuthenticationService.cs
  DuckCity.Application/Services/Interfaces/IRoomService.cs
  DuckCity.Application/Services/RoomService.cs
  DuckCity.Application/Validations/CheckValid.cs
  DuckCity.Domain/Exceptions/PlayersNotFoundException.cs
  DuckCity.Domain/Exceptions/RoomNotFoundException.cs
  DuckCity.Domain/Games/Game.cs
  DuckCity.Domain/Games/PlayerInGame.cs
  DuckCity.Domain/Rooms/PlayerInRoom.cs
  DuckCity.Domain/Rooms/Room.cs
  DuckCity.Domain/Users/Player.cs
  DuckCity.GameApi/Cache/Variables.cs
  DuckCity.GameApi/Controllers/WaitingRoomController.cs
  DuckCity.GameApi/DTO/UserIdAndRoomIdDto.cs
  DuckCity.GameApi/Dto/PlayerInWaitingRoomDto.cs
  DuckCity.GameApi/DuckCity.GameApi.csproj
  DuckCity.GameApi/Hub/CheckValid.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.GameApi/Hub/IDuckCityClient.cs
  DuckCity.GameApi/Hub/SignalRGroupManagement.cs
  DuckCity.GameApi/Hub/SignalRUser.cs
  DuckCity.GameApi/Mappings/MappingProfile.cs
  DuckCity.GameApi/Program.cs
  DuckCity.Infrastructure/Repositories/CacheImpl/GameRepository.cs
  DuckCity.Infrastructure/Repositories/CacheImpl/PlayerRepository.cs
  DuckCity.Infrastructure/Repositories/IGameRepository.cs
  DuckCity.Infrastructure/Repositories/IPlayerRepository.cs
  DuckCity.Infrastructure/Repositories/IRoomRepository.cs
  DuckCity.Infrastructure/Repositories/IUserRepository.cs
  DuckCity.Infrastructure/Repositories/MongoImpl/RoomRepository.cs
  DuckCity.Infrastructure/Repositories/MongoImpl/UserRepository.cs
  DuckCity.Tests/ConstantTest.cs
  DuckCity.Tests/Fake/ApiApplicationFake.cs
  DuckCity.Tests/Fake/MongoDbFake.cs
  DuckCity.Tests/IntegrationTests/Api/AuthenticationControllerIt.cs
  DuckCity.Tests/IntegrationTests/Infrastructure/UserRepositoryIt.cs
  DuckCity.Tests/UnitTests/Api/AuthenticationControllerUt.cs
  DuckCity.Tests/UnitTests/Api/RoomControllerUt.cs
  DuckCity.Tests/UnitTests/Application/RoomServiceUt.cs
  DuckCity.Tests/UnitTests/GameApi/DuckCityHubUt.cs
  DuckCity.Tests/UnitTests/GameApi/WaitingRoomControllerUt.cs
Labels: Backend, Improvement

#128 Refacto Players => Games
  DuckCity.Api/Program.cs
  DuckCity.Application/Services/Interfaces/IRoomService.cs
  DuckCity.Application/Services/RoomService.cs
  DuckCity.Domain/Games/Game.cs
  DuckCity.Domain/Users/Player.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.GameApi/Program.cs
  DuckCity.Infrastructure/Repositories/CacheImpl/GameRepository.cs
  DuckCity.Infrastructure/Repositories/CacheImpl/PlayerRepository.cs
  DuckCity.Infrastructure/Repositories/IGameRepository.cs
  DuckCity.Infrastructure/Repositories/IPlayerRepository.cs
  DuckCity.Tests/UnitTests/Application/RoomServiceUt.cs
Labels: Backend, Improvement

#129 127 Refacto Liste de games en cache (players à l'intérieur)
  DuckCity.Api/Controllers/AuthenticationController.cs
  DuckCity.Api/Controllers/RoomController.cs
  DuckCity.Api/Controllers/RoomPreviewController.cs
  DuckCity.Api/Controllers/SshController.cs
  DuckCity.Api/Program.cs
  DuckCity.Application/AuthenticationService/AuthenticationService.cs
  DuckCity.Application/AuthenticationService/IAuthenticationService.cs
  DuckCity.Application/RoomPreviewService/IRoomPreviewService.cs
  DuckCity.Application/RoomPreviewService/RoomPreviewService.cs
  DuckCity.Application/RoomService/IRoomService.cs
  DuckCity.Application/RoomService/RoomService.cs
  DuckCity.Application/Services/Interfaces/IAuthenticationService.cs
  DuckCity.Application/Services/Interfaces/IRoomService.cs
  DuckCity.Application/Services/RoomService.cs
  DuckCity.Application/Validations/CheckValid.cs
  DuckCity.Domain/Games/Game.cs
  DuckCity.Domain/Games/GameContainer.cs
  DuckCity.Domain/Rooms/Room.cs
  DuckCity.Domain/Rooms/RoomPreview.cs
  DuckCity.Domain/Rooms/RoomsContainer.cs
  DuckCity.GameApi/Dto/PlayerInWaitingRoomDto.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.GameApi/Program.cs
  DuckCity.Infrastructure/Repositories/CacheImpl/GameRepository.cs
  DuckCity.Infrastructure/Repositories/IGameRepository.cs
  DuckCity.Infrastructure/Repositories/IRoomRepository.cs
  DuckCity.Infrastructure/Repositories/IUserRepository.cs
  DuckCity.Infrastructure/Repositories/MongoImpl/RoomRepository.cs
  DuckCity.Infrastructure/Repositories/MongoImpl/UserRepository.cs
  DuckCity.Infrastructure/RoomPreviewRepository/IRoomPreviewRepository.cs
  DuckCity.Infrastructure/RoomPreviewRepository/RoomPreviewMongoRepository.cs
  DuckCity.Infrastructure/RoomRepository/IRoomRepository.cs
  DuckCity.Infrastructure/RoomRepository/RoomCacheRepository.cs
  DuckCity.Infrastructure/UserRepository/IUserRepository.cs
  DuckCity.Infrastructure/UserRepository/UserMongoRepository.cs
  DuckCity.Tests/DuckCity.Tests.csproj
  DuckCity.Tests/IntegrationTests/Infrastructure/UserRepositoryIt.cs
  DuckCity.Tests/UnitTests/Api/AuthenticationControllerUt.cs
  DuckCity.Tests/UnitTests/Api/RoomControllerUt.cs
  DuckCity.Tests/UnitTests/Application/RoomServiceUt.cs
Labels: Backend, Improvement

#136 Dockerfile game api
  DuckCity.Api/appsettings.Development.json
  DuckCity.GameApi/.dockerignore
  DuckCity.GameApi/Dockerfile
  DuckCity.GameApi/DuckCity.GameApi.csproj
  DuckCity.GameApi/Properties/launchSettings.json
  DuckCity.GameApi/appsettings.Development.json
Labels: Backend, Deployement

#147 84 Récupérer son statut lors de la reconnexion
  DuckCity.Api/Controllers/AuthenticationController.cs
  DuckCity.Api/DTO/Authentication/IdentifierDto.cs
  DuckCity.Api/DTO/Authentication/RegisterDto.cs
  DuckCity.Api/DTO/Authentication/TokenAndCurrentContainerIdDto.cs
  DuckCity.Api/DTO/Authentication/UserWithTokenDto.cs
  DuckCity.Api/Mappings/MappingProfile.cs
  DuckCity.Application/AuthenticationService/AuthenticationService.cs
  DuckCity.Application/AuthenticationService/IAuthenticationService.cs
  DuckCity.Application/RoomPreviewService/IRoomPreviewService.cs
  DuckCity.Application/RoomPreviewService/RoomPreviewService.cs
  DuckCity.Application/RoomService/IRoomService.cs
  DuckCity.Application/RoomService/RoomService.cs
  DuckCity.Domain/Users/User.cs
  DuckCity.GameApi/Controllers/GameController.cs
  DuckCity.GameApi/Dto/RoomCreationDto.cs
  DuckCity.GameApi/Dto/RoomDto.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.GameApi/Hub/IDuckCityClient.cs
  DuckCity.GameApi/Mappings/MappingProfile.cs
  DuckCity.Infrastructure/RoomPreviewRepository/IRoomPreviewRepository.cs
  DuckCity.Infrastructure/RoomPreviewRepository/RoomPreviewMongoRepository.cs
  DuckCity.Infrastructure/RoomRepository/IRoomRepository.cs
  DuckCity.Infrastructure/RoomRepository/RoomCacheRepository.cs
  DuckCity.Tests/IntegrationTests/Api/AuthenticationControllerIt.cs
  DuckCity.Tests/IntegrationTests/GameApi/DuckCityHubIt.cs
  DuckCity.Tests/UnitTests/Api/AuthenticationControllerUt.cs
  DuckCity.Tests/UnitTests/Application/RoomPreviewServiceUt.cs
  DuckCity.Tests/UnitTests/Application/RoomServiceUt.cs
  DuckCity.Tests/UnitTests/GameApi/DuckCityHubUt.cs
Labels: Backend, New feature

#150 149 Mettre en place les autorisations sur le Hub
  DuckCity.Api/Controllers/AuthenticationController.cs
  DuckCity.Application/Utils/UserUtils.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
Labels: Backend, Improvement

#151 68 Implémenter les fonctionnalités du jeu
  DuckCity.Application/GameService/GameService.cs
  DuckCity.Application/GameService/IGameService.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
Labels: Backend, Improvement

#156 154 Bug : Déconnexion fréquente de signalR dans le Onconnect
  DuckCity.Api/DTO/Authentication/TokenAndCurrentContainerIdDto.cs
  DuckCity.Infrastructure/RoomRepository/RoomCacheRepository.cs
Labels: Backend, Improvement

#157 155 Recuperer UserId depuis le context
  DuckCity.Api/Controllers/AuthenticationController.cs
  DuckCity.Api/Controllers/GameContainerController.cs
  DuckCity.Api/Controllers/UserController.cs
  DuckCity.Api/DTO/Room/RoomCreationDto.cs
  DuckCity.Api/DTO/Room/UserAndRoomDto.cs
  DuckCity.Api/DTO/User/UserChangePassword.cs
  DuckCity.Application/DuckCity.Application.csproj
  DuckCity.Application/UserService/IUserService.cs
  DuckCity.Application/Utils/UserUtils.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.Tests/ConstantTest.cs
  DuckCity.Tests/UnitTests/Api/UserControllerUt.cs
Labels: Backend, Improvement

#158 68 Implémenter les fonctionnalités du jeu
  DuckCity.Application/GameService/GameService.cs
  DuckCity.Application/GameService/IGameService.cs
  DuckCity.Application/Validations/CheckValid.cs
  DuckCity.Domain/Cards/BombCard.cs
  DuckCity.Domain/Cards/Card.cs
  DuckCity.Domain/Cards/GreenCard.cs
  DuckCity.Domain/Cards/YellowCard.cs
  DuckCity.Domain/Exceptions/GameAlreadyBeginException.cs
  DuckCity.Domain/Exceptions/GameFinishedException.cs
  DuckCity.Domain/Exceptions/PlayerNotAuthorizeException.cs
  DuckCity.Domain/Games/Game.cs
  DuckCity.Domain/Rooms/Room.cs
  DuckCity.Domain/Users/Player.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
  DuckCity.Tests/IntegrationTests/GameApi/DuckCityHubIt.cs
Labels: Backend, New feature

#161 141 Mettre en place le déploiement du backend
  .dockerignore
  DuckCity.Domain/DuckCity.Domain.csproj
Labels: Backend, Deployement

#160 159 Renommage Api GameContainer
  DuckCity.Api/Controllers/GameContainerController.cs
  DuckCity.Api/DTO/Room/RoomCreationDto.cs
Labels: Backend, Improvement

#165 164 Login renvoie userId et userName
  DuckCity.Api/Controllers/AuthenticationController.cs
  DuckCity.Api/DTO/Authentication/TokenAndCurrentContainerIdDto.cs
  DuckCity.Domain/Rooms/Room.cs
  DuckCity.GameApi/Hub/DuckCityHub.cs
Labels: Backend, Improvement
